"""empty message

Revision ID: 0d4ff5de6fde
Revises: 8da81afdfaa5
Create Date: 2021-05-09 12:14:52.835173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4ff5de6fde'
down_revision = '8da81afdfaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_id')
    # ### end Alembic commands ###
