"""empty message

Revision ID: 32c9e312c0f0
Revises: c23ef4656483
Create Date: 2021-05-09 11:40:41.448006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32c9e312c0f0'
down_revision = 'c23ef4656483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_column('product', 'id1')
    op.drop_column('product', 'id2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('id1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('product', 'product_id')
    op.drop_column('product', 'id')
    # ### end Alembic commands ###
