"""empty message

Revision ID: c23ef4656483
Revises: 364e896eca78
Create Date: 2021-05-09 09:50:41.407673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c23ef4656483'
down_revision = '364e896eca78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id1', sa.Integer(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('id2', sa.Integer(), nullable=False))
    op.drop_column('product', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('product', 'id2')
    op.drop_column('product', 'id1')
    # ### end Alembic commands ###
