"""empty message

Revision ID: c7ff19d0f662
Revises: dda25d8e0f27
Create Date: 2021-05-09 11:46:13.845603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ff19d0f662'
down_revision = 'dda25d8e0f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_id')
    # ### end Alembic commands ###
